package gh19009;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

public class Formulas extends javax.swing.JFrame {

    Administrador c1 = new Administrador();
    Sabores nuevo = new Sabores();
    DefaultListModel mIdSabor = new DefaultListModel();
    DefaultListModel mSabor = new DefaultListModel();
    DefaultListModel mId = new DefaultListModel();
    DefaultListModel mSaborS = new DefaultListModel();
    DefaultListModel mSeleccion = new DefaultListModel();
    private double porcentaje = 0.0;
    private boolean navegacion = false;
    private int ID;

    private Object[][] VerTsabor() {
        int posicion;
        Object sabores[][] = new Object[nuevo.c2.sabor().length][2];
        for (posicion = 0; posicion < nuevo.c2.sabor().length; posicion++) {
            sabores[posicion][0] = nuevo.c2.sabor()[posicion][0];
            sabores[posicion][1] = nuevo.c2.sabor()[posicion][1];
        }
        return sabores;
    }

    public Formulas() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/gh19009/imag.jpg")).getImage());
        this.getContentPane().setBackground(new Color(240, 226, 209));
        bSaNav.setVisible(navegacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lIdJugo = new javax.swing.JLabel();
        tfIdJugo = new javax.swing.JTextField();
        lnombreJugo = new javax.swing.JLabel();
        tfnombreJugo = new javax.swing.JTextField();
        lSabores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsIdJugo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsNombreJugo = new javax.swing.JList<>();
        lCantidad = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        lSelecSabor = new javax.swing.JLabel();
        lCantidadS = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsIdJugoS = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lsNombreJugoS = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lsCantidadS = new javax.swing.JList<>();
        bAgregarSabor = new javax.swing.JButton();
        lAviso = new javax.swing.JLabel();
        bProcesar = new javax.swing.JButton();
        bPrimero = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        bSiguiente = new javax.swing.JButton();
        bUltimo = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        bQuitar = new javax.swing.JButton();
        lNavegacion = new javax.swing.JLabel();
        bSaNav = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jugos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("framePrincipal"); // NOI18N

        lIdJugo.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        lIdJugo.setText("Id de jugo:");

        tfIdJugo.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        tfIdJugo.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tfIdJugoComponentAdded(evt);
            }
        });
        tfIdJugo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdJugoActionPerformed(evt);
            }
        });
        tfIdJugo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIdJugoKeyTyped(evt);
            }
        });

        lnombreJugo.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        lnombreJugo.setText("Nombre de jugo:");

        tfnombreJugo.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        tfnombreJugo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnombreJugoKeyTyped(evt);
            }
        });

        lSabores.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        lSabores.setText("Sabores disponibles:");

        lsIdJugo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(255, 204, 204)));
        lsIdJugo.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        lsIdJugo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lsIdJugo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lsIdJugoFocusGained(evt);
            }
        });
        lsIdJugo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsIdJugoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lsIdJugo);

        lsNombreJugo.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 204, 204)));
        lsNombreJugo.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        lsNombreJugo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lsNombreJugoFocusGained(evt);
            }
        });
        lsNombreJugo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsNombreJugoValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lsNombreJugo);

        lCantidad.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        lCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCantidad.setText("Cantidad:");

        tfCantidad.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCantidadKeyTyped(evt);
            }
        });

        lSelecSabor.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        lSelecSabor.setText("Sabores Seleccionados:");

        lCantidadS.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        lCantidadS.setText("Cantidad:");

        lsIdJugoS.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 204, 204)));
        lsIdJugoS.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        lsIdJugoS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lsIdJugoSFocusGained(evt);
            }
        });
        lsIdJugoS.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsIdJugoSValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lsIdJugoS);

        lsNombreJugoS.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 204, 204)));
        lsNombreJugoS.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        lsNombreJugoS.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsNombreJugoSValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lsNombreJugoS);

        lsCantidadS.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 204, 204)));
        lsCantidadS.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        lsCantidadS.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsCantidadSValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lsCantidadS);

        bAgregarSabor.setBackground(new java.awt.Color(201, 226, 201));
        bAgregarSabor.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        bAgregarSabor.setText("Agregar nuevo sabor");
        bAgregarSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarSaborActionPerformed(evt);
            }
        });

        lAviso.setFont(new java.awt.Font("Century Schoolbook", 1, 13)); // NOI18N
        lAviso.setForeground(new java.awt.Color(255, 0, 0));
        lAviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAviso.setText("Avisos ");
        lAviso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lAvisoFocusGained(evt);
            }
        });

        bProcesar.setBackground(new java.awt.Color(199, 224, 199));
        bProcesar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        bProcesar.setText("Procesar formula");
        bProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProcesarActionPerformed(evt);
            }
        });

        bPrimero.setBackground(new java.awt.Color(199, 224, 199));
        bPrimero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bPrimero.setText("|<");
        bPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrimeroActionPerformed(evt);
            }
        });

        bAtras.setBackground(new java.awt.Color(199, 224, 199));
        bAtras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bAtras.setText("<");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        bSiguiente.setBackground(new java.awt.Color(199, 224, 199));
        bSiguiente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bSiguiente.setText(">");
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });

        bUltimo.setBackground(new java.awt.Color(199, 224, 199));
        bUltimo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bUltimo.setText(">|");
        bUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUltimoActionPerformed(evt);
            }
        });

        bAgregar.setBackground(new java.awt.Color(199, 224, 199));
        bAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bAgregar.setText("--->");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bQuitar.setBackground(new java.awt.Color(199, 224, 199));
        bQuitar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bQuitar.setText("<---");
        bQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuitarActionPerformed(evt);
            }
        });

        lNavegacion.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        lNavegacion.setForeground(new java.awt.Color(255, 0, 0));

        bSaNav.setBackground(new java.awt.Color(255, 51, 51));
        bSaNav.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        bSaNav.setText("Salir");
        bSaNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaNavActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lnombreJugo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfnombreJugo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lIdJugo)
                                .addGap(32, 32, 32)
                                .addComponent(tfIdJugo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lSabores, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bAgregarSabor)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(327, 327, 327)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(52, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lSelecSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lCantidadS)
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63))))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lCantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bQuitar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bPrimero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bUltimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bSaNav)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bProcesar)
                                .addGap(102, 102, 102))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lIdJugo)
                    .addComponent(tfIdJugo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnombreJugo)
                    .addComponent(tfnombreJugo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCantidadS)
                            .addComponent(lSelecSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lSabores))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bQuitar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAgregarSabor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bPrimero)
                            .addComponent(bAtras)
                            .addComponent(bSiguiente)
                            .addComponent(bUltimo))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bProcesar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNavegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bSaNav)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdJugoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tfIdJugoComponentAdded

    }//GEN-LAST:event_tfIdJugoComponentAdded

    private void tfIdJugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdJugoActionPerformed

    }//GEN-LAST:event_tfIdJugoActionPerformed

    private void tfnombreJugoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnombreJugoKeyTyped
        char letra = evt.getKeyChar();
        String id = String.valueOf(c1.verIdjugos());
        if(navegacion == false)this.tfIdJugo.setText(id);
        if (!Character.isLetter(letra) && !Character.isSpaceChar(letra)) {
            evt.consume();
        }

    }//GEN-LAST:event_tfnombreJugoKeyTyped

    private void bAgregarSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarSaborActionPerformed
        if (navegacion == false) {
            nuevo.setVisible(true);
        }
    }//GEN-LAST:event_bAgregarSaborActionPerformed

    private void tfIdJugoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdJugoKeyTyped
        String id = String.valueOf(c1.verIdjugos());
        char letra = evt.getKeyChar();
        if(navegacion == false)this.tfIdJugo.setText(id);
        if (!Character.isLetter(letra) || Character.isLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfIdJugoKeyTyped

    private void lsIdJugoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lsIdJugoFocusGained
        mIdSabor.removeAllElements();
        int fila;//tomo el objeto del formulario de sabores y luego el objeto de la clase admiinistrador dentro de ese formulario
        for (fila = 0; fila < nuevo.c2.listarIdSabores().length; fila++) {
            mIdSabor.addElement(nuevo.c2.listarIdSabores()[fila]);
        }
        lsIdJugo.setModel(mIdSabor);
    }//GEN-LAST:event_lsIdJugoFocusGained

    private void lsNombreJugoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lsNombreJugoFocusGained
        mSabor.removeAllElements();
        int fila;
        for (fila = 0; fila < nuevo.c2.listarSabores().length; fila++) {
            mSabor.addElement(nuevo.c2.listarSabores()[fila]);
        }
        lsNombreJugo.setModel(mSabor);
    }//GEN-LAST:event_lsNombreJugoFocusGained

    private void lsIdJugoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsIdJugoValueChanged
        lsNombreJugo.setSelectedIndex(lsIdJugo.getSelectedIndex());
    }//GEN-LAST:event_lsIdJugoValueChanged

    private void lsNombreJugoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsNombreJugoValueChanged
        lsIdJugo.setSelectedIndex(lsNombreJugo.getSelectedIndex());
    }//GEN-LAST:event_lsNombreJugoValueChanged

    private void tfCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.' && navegacion == true) {
            evt.consume();
        }
        if ((evt.getKeyChar() == '.') && ((tfCantidad).getText().contains("."))) {
            evt.consume();
        }
    }//GEN-LAST:event_tfCantidadKeyTyped

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        if (navegacion == false && !tfCantidad.getText().isEmpty() && Double.parseDouble(tfCantidad.getText()) > 0 && Double.parseDouble(tfCantidad.getText()) <= 1.0) {
            mId.addElement(lsIdJugo.getSelectedValue());
            lsIdJugoS.setModel(mId);
            mSaborS.addElement(lsNombreJugo.getSelectedValue());
            lsNombreJugoS.setModel(mSaborS);
            mSeleccion.addElement(tfCantidad.getText());
            lsCantidadS.setModel(mSeleccion);
            porcentaje += Double.parseDouble(tfCantidad.getText());
            tfCantidad.setText("");
            String cantidad = "";
            if (porcentaje < 1.0) {
                cantidad = "Aviso: Falta " + (1.0 - porcentaje) + " para completar";
            } else if (porcentaje > 1.0) {
                cantidad = "Aviso: Se ha sobrepaso " + (porcentaje - 1.0);
            } else if (porcentaje == 1.0) {
                cantidad = "¡Formula Completa!";
            }
            lAviso.setText(cantidad);
        }
    }//GEN-LAST:event_bAgregarActionPerformed

    private void lAvisoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lAvisoFocusGained

    }//GEN-LAST:event_lAvisoFocusGained

    private void bQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuitarActionPerformed
        if (navegacion == false) {
            mId.remove(lsIdJugoS.getSelectedIndex());
            mSaborS.remove(lsNombreJugoS.getSelectedIndex());
            porcentaje -= Double.parseDouble(lsCantidadS.getSelectedValue());
            mSeleccion.remove(lsCantidadS.getSelectedIndex());
            String cantidad = "";
            if (porcentaje < 1.0) {
                cantidad = "Aviso: Falta " + (1.0 - porcentaje) + " para completar";
            } else if (porcentaje > 1.0) {
                cantidad = "Aviso: Se ha sobrepaso " + (porcentaje - 1.0);
            } else if (porcentaje == 1.0) {
                cantidad = "¡Formula Completa!";
            }
            lAviso.setText(cantidad);
        }
    }//GEN-LAST:event_bQuitarActionPerformed

    private void lsIdJugoSValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsIdJugoSValueChanged
        lsNombreJugoS.setSelectedIndex(lsIdJugoS.getSelectedIndex());
        lsCantidadS.setSelectedIndex(lsIdJugoS.getSelectedIndex());
    }//GEN-LAST:event_lsIdJugoSValueChanged

    private void lsNombreJugoSValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsNombreJugoSValueChanged
        lsIdJugoS.setSelectedIndex(lsNombreJugoS.getSelectedIndex());
        lsCantidadS.setSelectedIndex(lsNombreJugoS.getSelectedIndex());
    }//GEN-LAST:event_lsNombreJugoSValueChanged

    private void lsCantidadSValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsCantidadSValueChanged
        lsIdJugoS.setSelectedIndex(lsCantidadS.getSelectedIndex());
        lsNombreJugoS.setSelectedIndex(lsCantidadS.getSelectedIndex());
    }//GEN-LAST:event_lsCantidadSValueChanged

    private void bProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProcesarActionPerformed
        if (navegacion == false && porcentaje == 1.0 && !tfnombreJugo.getText().isEmpty()) {
            int posicion, idS, idJ = Integer.parseInt(tfIdJugo.getText());
            double cant;
            for (posicion = 0; posicion < mId.getSize(); posicion++) {
                idS = Integer.parseInt(String.valueOf(mId.getElementAt(posicion)));
                cant = Double.parseDouble(String.valueOf(mSeleccion.getElementAt(posicion)));
                c1.agregarMezclas(idJ, idS, cant);
            }
            c1.agregarJugo(tfnombreJugo.getText());
            ID = Integer.parseInt(tfIdJugo.getText());
            tfIdJugo.setText("");
            tfnombreJugo.setText("");
            mId.removeAllElements();
            mSaborS.removeAllElements();
            mSeleccion.removeAllElements();
            porcentaje = 0;
            lAviso.setText("Avisos");
        }
    }//GEN-LAST:event_bProcesarActionPerformed

    private void bPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrimeroActionPerformed
        this.navegacion = true;
        bSaNav.setVisible(navegacion);
        lNavegacion.setText("Navegacion activada");
        tfIdJugo.setEditable(false);
        tfnombreJugo.setEditable(false);
        mId.removeAllElements();
        mSaborS.removeAllElements();
        mSeleccion.removeAllElements();
        porcentaje = 0;
        lAviso.setText("");
        String id = String.valueOf(c1.verJugos()[0][0]);
        String nombre = String.valueOf(c1.verJugos()[0][1]);
        tfIdJugo.setText(id);
        tfnombreJugo.setText(nombre);
        idSa(c1.verJugos()[0][0]);
        cantidad(c1.verJugos()[0][0]);
        nomSabor();
    }//GEN-LAST:event_bPrimeroActionPerformed

    private DefaultListModel idSa(Object idJugo) {
        for (int posicion = 0; posicion < c1.verMezclas().length; posicion++) {
            if (c1.verMezclas()[posicion][0].equals(idJugo)) {
                mId.addElement(c1.verMezclas()[posicion][1]);
            }
        }
        mId.addElement("");
        return mId;
    }

    private DefaultListModel nomSabor() {
        int cuenta = 0, pos;
        while (cuenta < (mId.getSize()-1)) {
            for (pos = 0; pos < VerTsabor().length; pos++) {
                if (mId.get(cuenta).equals(VerTsabor()[pos][0])) {
                    mSaborS.addElement(VerTsabor()[pos][1]);
                    cuenta++;
                }
            }
        }
        return mSaborS;
    }

    private DefaultListModel cantidad(Object idJugo) {
        for (int posicion = 0; posicion < c1.verMezclas().length; posicion++) {
            if (c1.verMezclas()[posicion][0].equals(idJugo)) {
                mSeleccion.addElement(c1.verMezclas()[posicion][2]);
            }
        }
        return mSeleccion;
    }

    private void lsIdJugoSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lsIdJugoSFocusGained

    }//GEN-LAST:event_lsIdJugoSFocusGained

    private String nombreJugo(int id) {
        String nombre = "";
        nombre = String.valueOf(c1.verJugos()[id][1]);
        return nombre;
    }
    private void bUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUltimoActionPerformed
        this.navegacion = true;
        bSaNav.setVisible(navegacion);
        lNavegacion.setText("Navegacion activada");
        tfIdJugo.setEditable(false);
        tfnombreJugo.setEditable(false);
        mId.removeAllElements();
        mSaborS.removeAllElements();
        mSeleccion.removeAllElements();
        int id = (ID - 1);
        porcentaje = 0;
        lAviso.setText("");
        tfIdJugo.setText(String.valueOf(ID));
        tfnombreJugo.setText(nombreJugo(id));
        idSa(ID);
        cantidad(ID);
        nomSabor();
    }//GEN-LAST:event_bUltimoActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        this.navegacion = true;
        bSaNav.setVisible(navegacion);
        lNavegacion.setText("Navegacion activada");
        tfIdJugo.setEditable(false);
        tfnombreJugo.setEditable(false);
        mId.removeAllElements();
        mSaborS.removeAllElements();
        mSeleccion.removeAllElements();
        porcentaje = 0;
        lAviso.setText("");
        int id = Integer.parseInt(tfIdJugo.getText());
        if (id > 1) {
            id--;
            tfIdJugo.setText(String.valueOf(id));
            tfnombreJugo.setText(nombreJugo((id - 1)));
            idSa(id);
            cantidad(id);
            nomSabor();
        } else if(id == 0){
            String iD = String.valueOf(c1.verJugos()[0][0]);
            String nombre = String.valueOf(c1.verJugos()[0][1]);
            tfIdJugo.setText(iD);
            tfnombreJugo.setText(nombre);
            idSa(c1.verJugos()[0][0]);
            cantidad(c1.verJugos()[0][0]);
            nomSabor();
        }
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        this.navegacion = true;
        bSaNav.setVisible(navegacion);
        lNavegacion.setText("Navegacion activada");
        tfIdJugo.setEditable(false);
        tfnombreJugo.setEditable(false);
        mId.removeAllElements();
        mSaborS.removeAllElements();
        mSeleccion.removeAllElements();
        porcentaje = 0;
        lAviso.setText("");
        int id = Integer.parseInt(tfIdJugo.getText());
        if (id < ID) {
            id++;
            tfIdJugo.setText(String.valueOf(id));
            tfnombreJugo.setText(nombreJugo((id - 1)));
            idSa(id);
            cantidad(id);
            nomSabor();
        } else if (id > ID){
            tfIdJugo.setText(String.valueOf(ID));
            tfnombreJugo.setText(nombreJugo(id));
            idSa(ID);
            cantidad(ID);
            nomSabor();
        }
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void bSaNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaNavActionPerformed
        navegacion = false;
        mId.removeAllElements();
        mSaborS.removeAllElements();
        mSeleccion.removeAllElements();
        tfIdJugo.setEditable(true);
        tfnombreJugo.setEditable(true);
        String id = String.valueOf(c1.verIdjugos());
        this.tfIdJugo.setText(id);
        tfnombreJugo.setText("");
        lNavegacion.setText("");
        bSaNav.setVisible(navegacion);
    }//GEN-LAST:event_bSaNavActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bAgregarSabor;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bPrimero;
    private javax.swing.JButton bProcesar;
    private javax.swing.JButton bQuitar;
    private javax.swing.JButton bSaNav;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JButton bUltimo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lAviso;
    private javax.swing.JLabel lCantidad;
    private javax.swing.JLabel lCantidadS;
    private javax.swing.JLabel lIdJugo;
    private javax.swing.JLabel lNavegacion;
    private javax.swing.JLabel lSabores;
    private javax.swing.JLabel lSelecSabor;
    private javax.swing.JLabel lnombreJugo;
    private javax.swing.JList<String> lsCantidadS;
    private javax.swing.JList<String> lsIdJugo;
    private javax.swing.JList<String> lsIdJugoS;
    private javax.swing.JList<String> lsNombreJugo;
    private javax.swing.JList<String> lsNombreJugoS;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfIdJugo;
    private javax.swing.JTextField tfnombreJugo;
    // End of variables declaration//GEN-END:variables
}
